packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"
minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.8"
  - "@turbo/darwin-arm64@2.10.8"
  - "@turbo/linux-64@2.10.8"
  - "@turbo/linux-arm64@2.10.8"
  - "@turbo/windows-64@2.10.8"
  - "@turbo/windows-arm64@2.10.8"
  - turbo@2.10.8
  - "@oxc-parser/binding-android-arm-eabi@0.143.0"
  - "@oxc-parser/binding-android-arm64@0.143.0"
  - "@oxc-parser/binding-darwin-arm64@0.143.0"
  - "@oxc-parser/binding-darwin-x64@0.143.0"
  - "@oxc-parser/binding-freebsd-x64@0.143.0"
  - "@oxc-parser/binding-linux-arm-gnueabihf@0.143.0"
  - "@oxc-parser/binding-linux-arm-musleabihf@0.143.0"
  - "@oxc-parser/binding-linux-arm64-gnu@0.143.0"
  - "@oxc-parser/binding-linux-arm64-musl@0.143.0"
  - "@oxc-parser/binding-linux-ppc64-gnu@0.143.0"
  - "@oxc-parser/binding-linux-riscv64-gnu@0.143.0"
  - "@oxc-parser/binding-linux-riscv64-musl@0.143.0"
  - "@oxc-parser/binding-linux-s390x-gnu@0.143.0"
  - "@oxc-parser/binding-linux-x64-gnu@0.143.0"
  - "@oxc-parser/binding-linux-x64-musl@0.143.0"
  - "@oxc-parser/binding-openharmony-arm64@0.143.0"
  - "@oxc-parser/binding-win32-arm64-msvc@0.143.0"
  - "@oxc-parser/binding-win32-ia32-msvc@0.143.0"
  - "@oxc-parser/binding-win32-x64-msvc@0.143.0"
  - "@oxc-project/types@0.143.0"
  - "@rolldown/binding-android-arm64@1.2.2"
  - "@rolldown/binding-darwin-arm64@1.2.2"
  - "@rolldown/binding-darwin-x64@1.2.2"
  - "@rolldown/binding-freebsd-x64@1.2.2"
  - "@rolldown/binding-linux-arm-gnueabihf@1.2.2"
  - "@rolldown/binding-linux-arm64-gnu@1.2.2"
  - "@rolldown/binding-linux-arm64-musl@1.2.2"
  - "@rolldown/binding-linux-ppc64-gnu@1.2.2"
  - "@rolldown/binding-linux-s390x-gnu@1.2.2"
  - "@rolldown/binding-linux-x64-gnu@1.2.2"
  - "@rolldown/binding-linux-x64-musl@1.2.2"
  - "@rolldown/binding-openharmony-arm64@1.2.2"
  - "@rolldown/binding-win32-arm64-msvc@1.2.2"
  - "@rolldown/binding-win32-x64-msvc@1.2.2"
  - oxc-parser@0.143.0
  - rolldown@1.2.2
