export * from './schema';

// Database types are auto-generated by Supabase CLI.
// Run `pnpm --filter db db:types` to regenerate after schema changes.
// The generated file will be at ./database.types.ts
//
// Usage:
//   import type { Database } from '@plotpoint/db';
//   type Story = Database['public']['Tables']['stories']['Row'];
//   type NewStory = Database['public']['Tables']['stories']['Insert'];
//
// To set up type generation:
// 1. Run `supabase init` in project root
// 2. Run `supabase link --project-ref YOUR_PROJECT_REF`
// 3. Run `pnpm --filter db db:types`

// Re-export generated types when available
// export type { Database } from './database.types';
