// @ts-nocheck -- generated JavaScript is verified against its typed kernel.
/* oxlint-disable no-useless-escape -- Rolldown protects closing script tags. */
// GENERATED by Rolldown from web-runtime-kernel.ts. Run pnpm runtime:generate.
import { HOST_BRIDGE_VERSION } from "@plotpoint/protocol";
//#region src/runtime/web-runtime-kernel.ts
function deriveSharedCommandIntent(input, descriptor, model, projectionSchemaId, projection) {
  const canonical = (value) => {
    if (value === null || typeof value === "string" || typeof value === "boolean") return true;
    if (typeof value === "number") return Number.isFinite(value) && !Object.is(value, -0);
    if (Array.isArray(value)) return value.every(canonical);
    if (value === null || typeof value !== "object") return false;
    const prototype = Object.getPrototypeOf(value);
    return (
      (prototype === Object.prototype || prototype === null) &&
      Object.values(value).every(canonical)
    );
  };
  if (input === null || typeof input !== "object" || Array.isArray(input))
    throw new Error("runtime-shared-command-input-invalid");
  const commandInput = input;
  const required = ["commandId", "payload"];
  const allowed = /* @__PURE__ */ new Set([...required, "observationIds"]);
  const observationIds = commandInput.observationIds ?? [];
  if (
    required.some((key) => !Object.hasOwn(commandInput, key)) ||
    Object.keys(commandInput).some((key) => !allowed.has(key)) ||
    typeof commandInput.commandId !== "string" ||
    commandInput.commandId.length === 0 ||
    commandInput.payload === null ||
    typeof commandInput.payload !== "object" ||
    Array.isArray(commandInput.payload) ||
    !canonical(commandInput.payload) ||
    !Array.isArray(observationIds) ||
    observationIds.some((id) => typeof id !== "string" || id.length === 0) ||
    new Set(observationIds).size !== observationIds.length
  )
    throw new Error("runtime-shared-command-input-invalid");
  if (
    descriptor.execution !== "trusted-mechanic" ||
    descriptor.aggregateModel !== model.id ||
    model.authority !== "server" ||
    projection.schemaId !== projectionSchemaId ||
    projection.aggregateKind !== model.kind ||
    !Number.isSafeInteger(projection.stateVersion) ||
    projection.stateVersion < 0
  )
    throw new Error("runtime-shared-command-binding-invalid");
  return Object.freeze({
    commandId: commandInput.commandId,
    target: Object.freeze({
      aggregateKind: projection.aggregateKind,
      aggregateId: projection.aggregateId,
      schemaId: model.stateSchema.id,
    }),
    expectedStateVersion: projection.stateVersion,
    type: descriptor.type,
    payload: commandInput.payload,
    observationIds: Object.freeze([...observationIds]),
  });
}
function scriptString(value) {
  return JSON.stringify(value).replaceAll("<", "\\u003c");
}
function buildRuntimeBootstrap(input) {
  const logic = scriptString(input.logicSource);
  const presentation = scriptString(input.presentationSource);
  const gameComposition = scriptString(JSON.stringify(input.gameComposition ?? null));
  const content = scriptString(JSON.stringify(input.content ?? {}));
  const assets = scriptString(JSON.stringify(input.assets ?? {}));
  const sharedCommandIntentDeriver = deriveSharedCommandIntent.toString();
  const sharedBindingAvailable = input.sharedBindingAvailable === true ? "true" : "false";
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; connect-src 'none'; img-src data: blob:; media-src data: blob:; style-src 'unsafe-inline'; script-src 'unsafe-inline' blob:">
<style>html,body,#root{margin:0;min-height:100%;font-family:ui-rounded,Georgia,serif;background:#f4f0e6;color:#142d2a}button,input{font:inherit}</style></head>
<body><main id="root"></main><script>
const pending = new Map(); let sequence = 0;
const clearPending = (requestId, waiter) => {
  if (pending.get(requestId) !== waiter) return false;
  pending.delete(requestId);
  if (waiter.timer !== undefined) clearTimeout(waiter.timer);
  return true;
};
const send = (type, payload, deadline) => new Promise((resolve, reject) => {
  const requestId = 'web-' + (++sequence);
  const waiter = { resolve, reject, timer: undefined };
  pending.set(requestId, waiter);
  if (deadline !== undefined) {
    waiter.timer = setTimeout(() => {
      if (clearPending(requestId, waiter)) reject(new Error(deadline.code));
    }, deadline.timeoutMs);
  }
  try {
    window.ReactNativeWebView.postMessage(JSON.stringify({ version: ${HOST_BRIDGE_VERSION}, requestId, type, payload }));
  } catch (error) {
    if (clearPending(requestId, waiter)) reject(error);
  }
});
window.__plotpointReceive = (message) => {
  const parsed = typeof message === 'string' ? JSON.parse(message) : message;
  const waiter = pending.get(parsed.requestId);
  if (waiter && clearPending(parsed.requestId, waiter)) {
    parsed.type === 'host.error' ? waiter.reject(parsed.payload) : waiter.resolve(parsed.payload);
  }
  window.dispatchEvent(new CustomEvent('plotpoint-host', { detail: parsed }));
};
const cancelPending = () => {
  for (const [requestId, waiter] of [...pending.entries()]) {
    if (clearPending(requestId, waiter)) waiter.reject(new Error('runtime-disposed'));
  }
};
(async () => {
  const logicUrl = URL.createObjectURL(new Blob([${logic}], { type: 'text/javascript' }));
  const presentationUrl = URL.createObjectURL(new Blob([${presentation}], { type: 'text/javascript' }));
  const [logicModule, presentationModule] = await Promise.all([import(logicUrl), import(presentationUrl)]);
  const bootstrap = await send('runtime.ready', {});
  const isRecord = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
  const exactKeys = (value, expected) => {
    const actual = Object.keys(value).sort(); const wanted = [...expected].sort();
    return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]);
  };
  const allowedKeys = (value, required, optional = []) => {
    if (!isRecord(value) || required.some((key) => !Object.hasOwn(value, key))) return false;
    const allowed = new Set([...required, ...optional]);
    return Object.keys(value).every((key) => allowed.has(key));
  };
  const deepFreeze = (value) => {
    if (!isRecord(value) && !Array.isArray(value)) return value;
    for (const nested of Object.values(value)) deepFreeze(nested);
    return Object.freeze(value);
  };
  const deriveSharedCommandIntent = ${sharedCommandIntentDeriver};
  const schemaRegistryMatches = (descriptors, registry) =>
    Array.isArray(descriptors) && isRecord(registry) &&
    JSON.stringify(Object.keys(registry).sort()) ===
      JSON.stringify(descriptors.map(({ type }) => type).sort()) &&
    descriptors.every(({ type, schema }) => isRecord(registry[type]) && registry[type].id === schema.id);
  if (!exactKeys(logicModule, ['aggregateModels'])) {
    throw new Error('runtime-logic-root-invalid');
  }
  if (!exactKeys(presentationModule, ['application', 'components'])) {
    throw new Error('runtime-presentation-root-invalid');
  }
  const application = presentationModule.application;
  if (!isRecord(application) || !exactKeys(application, ['mount']) || typeof application.mount !== 'function') {
    throw new Error('runtime-application-definition-invalid');
  }
  const generatedComponents = presentationModule.components;
  if (!isRecord(generatedComponents) || Object.values(generatedComponents).some((value) => typeof value !== 'function')) {
    throw new Error('runtime-component-registry-invalid');
  }
  const composition = JSON.parse(${gameComposition});
  if (composition === null) throw new Error('runtime-game-composition-missing');
  if (!isRecord(composition) || !isRecord(composition.application) ||
      !Array.isArray(composition.application.components) ||
      !Array.isArray(composition.aggregateModels) || !Array.isArray(composition.commands) ||
      !Array.isArray(composition.progressions) || !Array.isArray(composition.components) ||
      !Array.isArray(composition.resources)) {
    throw new Error('runtime-game-composition-invalid');
  }
  const expectedComponentIds = composition.components.map(({ id }) => id).sort();
  const generatedComponentIds = Object.keys(generatedComponents).sort();
  if (JSON.stringify(expectedComponentIds) !== JSON.stringify(generatedComponentIds)) {
    throw new Error('runtime-component-registry-mismatch');
  }

  if (!allowedKeys(bootstrap, ['runId', 'releaseId', 'aggregate']) ||
      typeof bootstrap.runId !== 'string' || typeof bootstrap.releaseId !== 'string' ||
      !allowedKeys(bootstrap.aggregate, ['modelId', 'aggregateId', 'aggregateKind', 'schemaId', 'stateVersion', 'state'], ['progression']) ||
      typeof bootstrap.aggregate.modelId !== 'string' || typeof bootstrap.aggregate.aggregateId !== 'string' ||
      bootstrap.aggregate.aggregateKind !== 'player' || typeof bootstrap.aggregate.schemaId !== 'string' ||
      !Number.isSafeInteger(bootstrap.aggregate.stateVersion) || bootstrap.aggregate.stateVersion < 0 ||
      !isRecord(bootstrap.aggregate.state)) {
    throw new Error('runtime-bootstrap-invalid');
  }
  const generatedAggregateModels = logicModule.aggregateModels;
  if (!isRecord(generatedAggregateModels)) throw new Error('runtime-aggregate-model-registry-invalid');
  const localModelDescriptors = composition.aggregateModels.filter(({ authority }) => authority === 'local');
  const expectedLocalModelIds = localModelDescriptors.map(({ id }) => id).sort();
  if (JSON.stringify(Object.keys(generatedAggregateModels).sort()) !== JSON.stringify(expectedLocalModelIds)) {
    throw new Error('runtime-aggregate-model-registry-mismatch');
  }
  const localModelDescriptor = localModelDescriptors.find(({ id }) => id === bootstrap.aggregate.modelId);
  const generatedLocalModel = generatedAggregateModels[bootstrap.aggregate.modelId];
  const localCommandDescriptors = composition.commands.filter(({ execution, aggregateModel }) =>
    execution === 'local' && aggregateModel === bootstrap.aggregate.modelId
  );
  const localProgressionDescriptor = composition.progressions.find(
    ({ aggregateModel }) => aggregateModel === bootstrap.aggregate.modelId
  );
  if (!localModelDescriptor || !isRecord(generatedLocalModel) ||
      generatedLocalModel.modelId !== localModelDescriptor.id ||
      generatedLocalModel.aggregateKind !== 'player' || generatedLocalModel.authority !== 'local' ||
      !isRecord(generatedLocalModel.stateSchema) ||
      generatedLocalModel.stateSchema.id !== localModelDescriptor.stateSchema.id ||
      bootstrap.aggregate.schemaId !== localModelDescriptor.stateSchema.id ||
      !isRecord(generatedLocalModel.commandContracts) ||
      !schemaRegistryMatches(localModelDescriptor.events, generatedLocalModel.eventSchemas) ||
      !schemaRegistryMatches(localModelDescriptor.effects, generatedLocalModel.effectSchemas) ||
      typeof generatedLocalModel.execute !== 'function' ||
      (localProgressionDescriptor === undefined
        ? generatedLocalModel.progression !== undefined
        : !isRecord(generatedLocalModel.progression) ||
          generatedLocalModel.progression.graphId !== localProgressionDescriptor.id)) {
    throw new Error('runtime-aggregate-model-selection-mismatch');
  }
  if (JSON.stringify(Object.keys(generatedLocalModel.commandContracts).sort()) !==
      JSON.stringify(localCommandDescriptors.map(({ type }) => type).sort())) {
    throw new Error('runtime-local-command-registry-mismatch');
  }

  let currentLocalView = deepFreeze({ ...bootstrap.aggregate });
  const localListeners = new Set();
  function canonicalFingerprintValue(value) {
    if (Array.isArray(value)) return value.map(canonicalFingerprintValue);
    if (value === null || typeof value === 'string' || typeof value === 'boolean') return value;
    if (typeof value === 'number' && Number.isFinite(value) && !Object.is(value, -0)) return value;
    if (!isRecord(value) ||
        (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null)) {
      throw new Error('runtime-local-command-input-invalid');
    }
    return Object.fromEntries(
      Object.keys(value).sort().map((key) => [key, canonicalFingerprintValue(value[key])])
    );
  }
  const canonicalFingerprint = (value) => JSON.stringify(canonicalFingerprintValue(value));
  const diagnosticCodes = (diagnostics, fallback) => {
    if (!Array.isArray(diagnostics)) return [fallback];
    const codes = diagnostics.map((diagnostic) => isRecord(diagnostic) ? diagnostic.code : undefined);
    return codes.length > 0 && codes.every((code) => typeof code === 'string' && code.length > 0)
      ? codes
      : [fallback];
  };
  const prepareLocalCandidate = (descriptor, commandInput) => {
    const observations = commandInput.observations ?? [];
    if (!Array.isArray(observations) || observations.some((observation) =>
      !isRecord(observation) || typeof observation.observationId !== 'string' ||
      typeof observation.kind !== 'string' || typeof observation.key !== 'string' ||
      !Object.hasOwn(observation, 'value')
    )) {
      throw new Error('runtime-local-observation-reference-invalid');
    }
    const execution = generatedLocalModel.execute({
      aggregate: currentLocalView,
      command: Object.freeze({
        id: commandInput.commandId,
        type: descriptor.type,
        target: Object.freeze({ kind: 'player', id: currentLocalView.aggregateId }),
        expectedStateVersion: currentLocalView.stateVersion,
        payload: commandInput.payload
      }),
      observations: observations.map(({ kind, key, value }) => Object.freeze({ kind, key, value }))
    });
    if (!isRecord(execution)) throw new Error('runtime-local-execution-result-invalid');
    if (execution.kind === 'preflight-invalid') {
      return Object.freeze({
        commandId: commandInput.commandId,
        disposition: 'not-recorded',
        terminal: 'invalid',
        phase: 'preflight',
        diagnosticCodes: Object.freeze(diagnosticCodes(execution.diagnostics, 'runtime-local-preflight-invalid'))
      });
    }
    if (execution.kind !== 'recorded' || !isRecord(execution.record) ||
        !isRecord(execution.aggregate) || !isRecord(execution.aggregate.state)) {
      throw new Error('runtime-local-execution-result-invalid');
    }
    const record = execution.record;
    if (!isRecord(record.command) || record.command.id !== commandInput.commandId ||
        record.command.type !== descriptor.type || !isRecord(record.command.target) ||
        record.command.target.kind !== 'player' ||
        record.command.target.id !== currentLocalView.aggregateId ||
        record.command.expectedStateVersion !== currentLocalView.stateVersion ||
        !isRecord(record.command.payload) ||
        !Number.isSafeInteger(record.priorStateVersion) ||
        !Number.isSafeInteger(record.resultingStateVersion) ||
        record.priorStateVersion !== currentLocalView.stateVersion ||
        record.resultingStateVersion !== execution.aggregate.stateVersion) {
      throw new Error('runtime-local-execution-record-invalid');
    }
    const base = {
      commandId: commandInput.commandId,
      modelId: generatedLocalModel.modelId,
      commandType: descriptor.type,
      payload: record.command.payload,
      target: Object.freeze({
        aggregateId: currentLocalView.aggregateId,
        aggregateKind: 'player',
        schemaId: currentLocalView.schemaId
      }),
      expectedStateVersion: record.priorStateVersion,
      observationIds: Object.freeze(observations.map(({ observationId }) => observationId)),
      consumedObservationIds: Object.freeze(
        Array.isArray(record.observationTrace)
          ? record.observationTrace.map(({ index }) => observations[index]?.observationId).filter((id) => typeof id === 'string')
          : []
      )
    };
    if (record.terminal === 'accepted') {
      if (!isRecord(record.outcome) || !Array.isArray(record.domainEvents) ||
          !Array.isArray(record.effectIntents) || !Array.isArray(record.progressionTrace)) {
        throw new Error('runtime-local-execution-record-invalid');
      }
      const stateChanged = JSON.stringify(currentLocalView.state) !== JSON.stringify(execution.aggregate.state);
      const progressionChanged = JSON.stringify(currentLocalView.progression) !== JSON.stringify(execution.aggregate.progression);
      if (progressionChanged && execution.aggregate.progression === undefined) {
        throw new Error('runtime-local-execution-record-invalid');
      }
      return deepFreeze({
        ...base,
        terminal: 'accepted',
        ...(stateChanged ? { nextState: execution.aggregate.state } : {}),
        ...(progressionChanged ? { nextProgression: execution.aggregate.progression } : {}),
        outcome: record.outcome,
        domainEvents: record.domainEvents,
        effectIntents: record.effectIntents,
        progressionTrace: record.progressionTrace
      });
    }
    if (record.terminal === 'no-op' || record.terminal === 'rejected') {
      if (!isRecord(record.outcome)) throw new Error('runtime-local-execution-record-invalid');
      return deepFreeze({ ...base, terminal: record.terminal, outcome: record.outcome });
    }
    if (record.terminal === 'invalid') {
      return deepFreeze({
        ...base,
        terminal: 'invalid',
        phase: 'execution',
        diagnosticCodes: diagnosticCodes(record.diagnostics, 'runtime-local-execution-invalid'),
        attemptedProgressionTrace: Array.isArray(record.progressionTrace) ? record.progressionTrace : []
      });
    }
    throw new Error('runtime-local-execution-record-invalid');
  };
  const localCommandAttempts = new Map();
  let localCommandLane = Promise.resolve();
  let localCommandLaneOpen = true;
  const executeLocalCommand = async (descriptor, commandInput) => {
    const candidate = prepareLocalCandidate(descriptor, commandInput);
    if (candidate.disposition === 'not-recorded') return candidate;
    const result = await send('transition.commit', { candidate }, {
      timeoutMs: 15_000,
      code: 'runtime-local-transition-response-timeout'
    });
    if (!isRecord(result) || result.commandId !== commandInput.commandId ||
        result.terminal !== candidate.terminal ||
        (result.disposition !== 'committed' && result.disposition !== 'duplicate') ||
        !Number.isSafeInteger(result.resultingStateVersion)) {
      throw new Error('runtime-local-transition-result-invalid');
    }
    if (result.terminal === 'accepted') {
      if (result.disposition === 'duplicate' &&
          result.resultingStateVersion === currentLocalView.stateVersion) {
        return result;
      }
      if (result.resultingStateVersion !== currentLocalView.stateVersion + 1) {
        throw new Error('runtime-local-transition-version-invalid');
      }
      currentLocalView = deepFreeze({
        ...currentLocalView,
        stateVersion: result.resultingStateVersion,
        ...(candidate.nextState === undefined ? {} : { state: candidate.nextState }),
        ...(candidate.nextProgression === undefined ? {} : { progression: candidate.nextProgression })
      });
      for (const listener of [...localListeners]) {
        try { listener(); } catch (error) { console.warn('runtime-local-listener-failed', error); }
      }
    }
    return result;
  };
  const localCommandRegistry = Object.freeze(Object.fromEntries(
    localCommandDescriptors.map((descriptor) => {
      const contract = generatedLocalModel.commandContracts[descriptor.type];
      if (!isRecord(contract) || contract.registrationId !== descriptor.id ||
          !isRecord(contract.payloadSchema) || contract.payloadSchema.id !== descriptor.payloadSchema.id ||
          !isRecord(contract.outcomeSchema) || contract.outcomeSchema.id !== descriptor.outcomeSchema.id) {
        throw new Error('runtime-local-command-registry-mismatch:' + descriptor.id);
      }
      return [descriptor.id, Object.freeze({
        execute(commandInput) {
          if (!localCommandLaneOpen) throw new Error('runtime-local-command-lane-closed');
          if (!allowedKeys(commandInput, ['commandId', 'payload'], ['observations']) ||
              typeof commandInput.commandId !== 'string' || commandInput.commandId.length === 0 ||
              !isRecord(commandInput.payload)) {
            throw new Error('runtime-local-command-input-invalid');
          }
          const fingerprint = descriptor.id + '\0' + canonicalFingerprint(commandInput);
          const prior = localCommandAttempts.get(commandInput.commandId);
          if (prior !== undefined) {
            if (prior.fingerprint !== fingerprint) {
              throw new Error('runtime-local-command-identity-conflict');
            }
            if (prior.result !== undefined) return prior.result;
          }
          const result = localCommandLane.then(() => {
            if (!localCommandLaneOpen) throw new Error('runtime-local-command-lane-closed');
            return executeLocalCommand(descriptor, commandInput);
          });
          localCommandAttempts.set(commandInput.commandId, Object.freeze({ fingerprint, result }));
          localCommandLane = result.then(
            () => undefined,
            () => {
              const current = localCommandAttempts.get(commandInput.commandId);
              if (current !== undefined && current.result === result) {
                localCommandAttempts.set(commandInput.commandId, Object.freeze({ fingerprint }));
              }
            }
          );
          return result;
        }
      })];
    })
  ));
  const local = Object.freeze({
    async getView() { return currentLocalView; },
    onChanged(listener) {
      if (typeof listener !== 'function') throw new Error('runtime-local-listener-invalid');
      localListeners.add(listener); let subscribed = true;
      return () => { if (subscribed) { subscribed = false; localListeners.delete(listener); } };
    },
    commands: localCommandRegistry
  });
  void local.getView;
  void local.onChanged;

  const cleanupStack = [];
  let acceptingCleanup = true;
  let cleanupPromise;
  const lifecycle = Object.freeze({
    defer(cleanup) {
      if (!acceptingCleanup) throw new Error('runtime-mount-scope-closed');
      if (typeof cleanup !== 'function') throw new Error('runtime-component-cleanup-invalid');
      cleanupStack.push({ cleanup, invoked: false });
    }
  });
  const cleanupMountScope = () => {
    if (cleanupPromise) return cleanupPromise;
    acceptingCleanup = false;
    cleanupPromise = (async () => {
      const failures = [];
      const reverseCleanup = cleanupStack.reverse();
      for (const entry of reverseCleanup) {
        try {
          if (entry.invoked) throw new Error('runtime-component-cleanup-already-invoked');
          entry.invoked = true;
          await entry.cleanup();
        } catch (error) { failures.push(error); }
      }
      if (failures.length > 0) throw new Error('runtime-mount-cleanup-failed');
    })();
    return cleanupPromise;
  };

  const select = (source, ids, code) => Object.freeze(Object.fromEntries(ids.map((id) => {
    if (!Object.hasOwn(source, id)) throw new Error(code + ':' + id);
    return [id, source[id]];
  })));
  const contentRegistry = deepFreeze(JSON.parse(${content}));
  const assetRegistry = deepFreeze(JSON.parse(${assets}));
  if (!isRecord(contentRegistry) || !isRecord(assetRegistry)) {
    throw new Error('runtime-resource-registry-invalid');
  }
  const createCapabilityClient = (capability) => Object.freeze({
      async request(requestInput) {
        const expected = { id: capability.id, major: capability.major, minor: capability.minimumMinor };
        const result = await send('capability.request', { capability: expected, input: requestInput });
        if (!allowedKeys(result, ['capability', 'output']) || !isRecord(result.capability) ||
            result.capability.id !== expected.id || result.capability.major !== expected.major ||
            result.capability.minor !== expected.minor || !isRecord(result.output)) {
          throw new Error('runtime-capability-result-invalid:' + capability.id);
        }
        return deepFreeze(result.output);
      }
    });
  const sharedListeners = new Set();
  const onSharedSyncChanged = (event) => {
    if (event.detail && event.detail.type === 'shared.sync.changed') {
      for (const listener of [...sharedListeners]) {
        try { listener(); } catch (error) { console.warn('runtime-shared-listener-failed', error); }
      }
    }
  };
  window.addEventListener('plotpoint-host', onSharedSyncChanged);
  lifecycle.defer(() => window.removeEventListener('plotpoint-host', onSharedSyncChanged));
  const componentFactories = Object.create(null);
  let componentMountFailure;
  for (const componentId of composition.application.components) {
    const componentDescriptor = composition.components.find(({ id }) => id === componentId);
    const implementation = generatedComponents[componentId];
    if (!componentDescriptor || typeof implementation !== 'function') {
      throw new Error('runtime-application-component-missing:' + componentId);
    }
    componentFactories[componentId] = () => {
      let componentMounting = true;
      const componentLifecycle = Object.freeze({
        defer(cleanup) {
          if (!componentMounting) throw new Error('runtime-component-mount-scope-closed');
          if (typeof cleanup !== 'function') throw new Error('runtime-component-cleanup-invalid');
          lifecycle.defer(cleanup);
        }
      });
      const localCommandIds = componentDescriptor.commands.filter((commandId) =>
        composition.commands.find(({ id }) => id === commandId)?.execution === 'local'
      );
      const sharedCommandIds = componentDescriptor.commands.filter((commandId) =>
        composition.commands.find(({ id }) => id === commandId)?.execution === 'trusted-mechanic'
      );
      const context = {
        lifecycle: componentLifecycle,
        local: Object.freeze({
          getView: local.getView,
          onChanged: local.onChanged,
          commands: select(local.commands, localCommandIds, 'runtime-component-local-command-missing')
        }),
        content: select(contentRegistry, componentDescriptor.content, 'runtime-component-content-missing'),
        assets: select(assetRegistry, componentDescriptor.assets, 'runtime-component-asset-missing'),
        capabilities: Object.freeze(Object.fromEntries(
          componentDescriptor.capabilities.map((capability) =>
            [capability.id, createCapabilityClient(capability)]
          )
        ))
      };
      if (componentDescriptor.sharedProjection !== undefined && ${sharedBindingAvailable}) {
        const mechanic = composition.trustedMechanic;
        const sharedModel = mechanic && composition.aggregateModels.find(({ id }) => id === mechanic.aggregateModel);
        if (!isRecord(mechanic) || !isRecord(sharedModel) || sharedModel.authority !== 'server' ||
            mechanic.projectionSchema.id !== componentDescriptor.sharedProjection.id) {
          throw new Error('runtime-component-shared-binding-invalid:' + componentId);
        }
        context.shared = Object.freeze({
          getView: () => send('shared.view.get', {}),
          onSyncChanged(listener) {
            sharedListeners.add(listener); let subscribed = true;
            return () => { if (subscribed) { subscribed = false; sharedListeners.delete(listener); } };
          },
          commands: Object.freeze(Object.fromEntries(sharedCommandIds.map((commandId) => {
            const descriptor = composition.commands.find(({ id }) => id === commandId);
            if (!descriptor || !mechanic.commands.includes(commandId) ||
                descriptor.execution !== 'trusted-mechanic' || descriptor.aggregateModel !== sharedModel.id) {
              throw new Error('runtime-component-shared-command-missing:' + componentId + ':' + commandId);
            }
            return [commandId, Object.freeze({
              async execute(commandInput) {
                if (!allowedKeys(commandInput, ['commandId', 'payload'], ['observationIds'])) {
                  throw new Error('runtime-shared-command-input-invalid');
                }
                const view = await send('shared.view.get', {});
                if (!isRecord(view) || !Array.isArray(view.projections)) {
                  throw new Error('runtime-shared-view-invalid');
                }
                const projections = view.projections.filter((projection) =>
                  isRecord(projection) && projection.schemaId === componentDescriptor.sharedProjection.id &&
                  projection.aggregateKind === sharedModel.kind
                );
                if (projections.length !== 1) throw new Error('runtime-shared-projection-invalid');
                const command = deriveSharedCommandIntent(
                  commandInput,
                  descriptor,
                  sharedModel,
                  componentDescriptor.sharedProjection.id,
                  projections[0]
                );
                return send('shared.command.enqueue', { command });
              }
            })];
          })))
        });
      }
      let element;
      try {
        element = implementation(Object.freeze(context));
        if (!(element instanceof HTMLElement)) {
          throw new Error('runtime-component-element-invalid:' + componentId);
        }
      } catch (error) {
        componentMountFailure ??= error;
        throw error;
      } finally { componentMounting = false; }
      return element;
    };
  }

  const root = document.getElementById('root');
  if (!(root instanceof HTMLElement)) throw new Error('runtime-application-root-invalid');
  const components = Object.freeze(componentFactories);
  let applicationHandle;
  try {
    applicationHandle = await application.mount({ root, components });
    if (componentMountFailure !== undefined) throw componentMountFailure;
    if (!isRecord(applicationHandle) || !exactKeys(applicationHandle, ['unmount']) || typeof applicationHandle.unmount !== 'function') {
      throw new Error('runtime-application-handle-invalid');
    }
    acceptingCleanup = false;
  } catch (error) {
    try { await cleanupMountScope(); } catch { throw new Error('runtime-mount-rollback-failed'); }
    throw error;
  }

  let disposalPromise;
  const disposeRuntime = () => {
    if (disposalPromise) return disposalPromise;
    disposalPromise = (async () => {
      const failures = [];
      localCommandLaneOpen = false;
      cancelPending();
      await localCommandLane;
      try { await applicationHandle.unmount(); } catch (error) { failures.push(error); }
      try { await cleanupMountScope(); } catch (error) { failures.push(error); }
      localCommandAttempts.clear();
      if (failures.length > 0) throw new Error('runtime-application-unmount-failed');
    })();
    return disposalPromise;
  };
  window.__plotpointDispose = disposeRuntime;
  window.addEventListener('pagehide', () => { void disposeRuntime(); }, { once: true });
})().catch((error) => { document.getElementById('root').textContent = 'Runtime failed: ' + String(error && error.message || error); });
<\/script></body></html>`;
}
function allowRuntimeNavigation(url) {
  return url === "about:blank" || url.startsWith("blob:");
}
//#endregion
export { allowRuntimeNavigation, buildRuntimeBootstrap, deriveSharedCommandIntent };
